#!/bin/sh
# curl scripts to hit the github api
#VARIABLES
SEARCH_1='AWS c4.xlarge'
SEARCH_2='AWS c4.2xlarge'
SEARCH_3='AWS c4.4xlarge'
SEARCH_4='AWS c4.8xlarge'
SEARCH_5='AWS c3.large'
SEARCH_6='AWS c3.xlarge'
SEARCH_7='AWS c3.2xlarge'
SEARCH_8='AWS c3.4xlarge'
SEARCH_9='AWS c3.8xlarge'
SEARCH_10='GCE n1-highcpu-2'
SEARCH_11='GCE n1-highcpu-4'
SEARCH_12='GCE n1-highcpu-8'
SEARCH_13='GCE n1-highcpu-16'
SEARCH_14='GCE n1-highcpu-321'

SEARCH=$SEARCH_1

#TESTING
current_ip="$(curl --silent --show-error --fail ipecho.net/plain)"
echo "IP: $current_ip"

#ISSUES
curl -G https://api.github.com/search/issues \
 --data-urlencode "q=$SEARCH" \
 --data-urlencode "sort=updated" \
 --data-urlencode "order=desc" \
 -H "Accept: application/vnd.github.preview" | jq ".items[0,1,2] | {title, user, html_url, created_at, updated_at}"
 
 
 #BROKEN: -H "Accept: application/vnd.github.preview" | jq ".items[0] | {title, user.login, user.html_url, html_url, created_at, updated_at}"
 #try user.login, user.htmlurl

#WORKS

#REPOSITORIES
#curl -G https://api.github.com/search/repositories \
 #--data-urlencode "q=created:>`date -v-7d '+%Y-%m-%d'`" \
 #--data-urlencode "sort=stars" \
 #--data-urlencode "order=desc" \
 #-H "Accept: application/vnd.github.preview" | jq ".items[0,1,2] | {name, description, language, watchers_count, html_url}"

#curl -G https://api.github.com/search/repositories       --data-urlencode 'q=@jeresig -language:javascript'     -H 'Accept: application/vnd.github.preview'            | jq '.items[] | {html_url, watchers_count, language, name}'

#curl -G https://api.github.com/search/repositories           --data-urlencode "q=created:>`date -v-7d '+%Y-%m-%d'`"     --data-urlencode "sort=stars"                              --data-urlencode "order=desc"                              -H "Accept: application/vnd.github.preview"                | jq ".items[0,1,2] | {name, description, language, watchers_count, html_url}"
